# Generated by Django 5.1.7 on 2025-03-24 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cim', models.CharField(max_length=255)),
                ('kep', models.ImageField(upload_to='hirek/')),
                ('datum', models.DateTimeField(auto_now_add=True)),
                ('tartalom', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Hír',
                'verbose_name_plural': 'Hírek',
            },
        ),
    ]
