# Generated by Django 5.1.7 on 2025-03-24 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hirek', '0002_alter_hir_options_remove_hir_datum_remove_hir_kep_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hir',
            name='cim',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='hir',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
