# Generated by Django 5.1.7 on 2025-03-24 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hirek', '0004_alter_hir_kiemelt_kep'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meccs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipus', models.CharField(choices=[('EREDMENY', 'Eredmény'), ('KOVETKEZO', 'Következő meccs')], max_length=10)),
                ('korosztaly', models.CharField(max_length=50)),
                ('hazai_csapat', models.CharField(max_length=100)),
                ('vendeg_csapat', models.CharField(max_length=100)),
                ('eredmeny', models.CharField(blank=True, max_length=20)),
                ('datum', models.DateField()),
                ('helyszin', models.CharField(blank=True, max_length=100)),
                ('idopont', models.TimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Meccsek',
                'ordering': ['-datum'],
            },
        ),
    ]
