# Generated by Django 5.2.1 on 2025-05-16 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hirek', '0005_meccs'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Dokumentum neve')),
                ('file', models.FileField(upload_to='pdfs/', verbose_name='PDF fájl')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Feltöltve')),
            ],
            options={
                'verbose_name': 'PDF dokumentum',
                'verbose_name_plural': 'PDF dokumentumok',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
