# Generated by Django 5.1.7 on 2025-03-24 14:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hirek', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hir',
            options={'ordering': ['-letrehozva'], 'verbose_name_plural': 'Hírek'},
        ),
        migrations.RemoveField(
            model_name='hir',
            name='datum',
        ),
        migrations.RemoveField(
            model_name='hir',
            name='kep',
        ),
        migrations.AddField(
            model_name='hir',
            name='kiemelt_kep',
            field=models.ImageField(blank=True, upload_to='hirek_kepek/'),
        ),
        migrations.AddField(
            model_name='hir',
            name='letrehozva',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='hir',
            name='publikalt',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hir',
            name='slug',
            field=models.SlugField(default='temp-slug', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='hir',
            name='cim',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='hir',
            name='tartalom',
            field=models.TextField(),
        ),
    ]
