# Generated by Django 5.1.7 on 2025-03-24 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hirek', '0003_alter_hir_cim_alter_hir_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hir',
            name='kiemelt_kep',
            field=models.ImageField(blank=True, null=True, upload_to='media/hirek_kepek'),
        ),
    ]
