# Generated by Django 5.2.1 on 2025-05-21 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hirek', '0006_pdfdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='Korosztaly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nev', models.CharField(max_length=250, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('vezeto_edzo', models.CharField(max_length=250)),
                ('asszisztens_edzo', models.CharField(blank=True, max_length=250)),
                ('banner_kep', models.ImageField(blank=True, null=True, upload_to='korosztaly_banner/')),
            ],
            options={
                'verbose_name': 'Korosztaly',
                'verbose_name_plural': 'Korosztalyok',
            },
        ),
        migrations.CreateModel(
            name='Jatekos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nev', models.CharField(max_length=250)),
                ('poszt', models.CharField(choices=[('K', 'Kapus'), ('V', 'Védő'), ('KP', 'Középpályás'), ('T', 'Támadó')], max_length=2)),
                ('mezszam', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('korosztaly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jatekosok', to='hirek.korosztaly')),
            ],
            options={
                'verbose_name': 'Jatekos',
                'verbose_name_plural': 'Jatekosok',
            },
        ),
    ]
