# Generated by Django 5.2.1 on 2025-05-22 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hirek', '0007_korosztaly_jatekos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edzo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nev', models.CharField(max_length=250, verbose_name='Név')),
                ('pozicio', models.CharField(max_length=250, verbose_name='Pozíció')),
                ('tipus', models.CharField(choices=[('edzo', 'Edző'), ('szakmai', 'Szakmai Stáb')], max_length=10, verbose_name='Típus')),
            ],
            options={
                'verbose_name': 'Edző/Szakmai tag',
                'verbose_name_plural': 'Edzők/Szakmai stáb',
            },
        ),
    ]
