# Generated by Django 5.2.1 on 2025-05-23 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hirek', '0008_edzo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='korosztaly',
            options={'ordering': ['sorrend'], 'verbose_name': 'Korosztály', 'verbose_name_plural': 'Korosztályok'},
        ),
        migrations.RemoveField(
            model_name='korosztaly',
            name='asszisztens_edzo',
        ),
        migrations.RemoveField(
            model_name='korosztaly',
            name='banner_kep',
        ),
        migrations.RemoveField(
            model_name='korosztaly',
            name='vezeto_edzo',
        ),
        migrations.AddField(
            model_name='edzo',
            name='korosztalyok',
            field=models.ManyToManyField(blank=True, to='hirek.korosztaly', verbose_name='Vezetett korosztályok'),
        ),
        migrations.AddField(
            model_name='korosztaly',
            name='sorrend',
            field=models.PositiveIntegerField(default=0, verbose_name='Sorrend'),
        ),
        migrations.AlterField(
            model_name='korosztaly',
            name='nev',
            field=models.CharField(max_length=100, verbose_name='Korosztály neve'),
        ),
    ]
